on: [push]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - id: backend-deployment
      uses: Zimboboys/express-deployment-aws@v0.1.0
      with:
        s3-bucket: 'example-api-deployment'
        stack-name: 'example-api-deployment-proj'
      env:
        CLIENT_URL: ${{ secrets.CLIENT_URL }}
        API_URL: ${{ secrets.API_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    - run: echo API is at ${{ steps.backend-deployment.outputs.api-url }}
      shell: bash
